apiVersion: v1
kind: Service
metadata:
  name: mongo-order-svc
  namespace: dev
  labels:
    name: mongo-order-svc
spec:
  clusterIP: None
  selector:
    role: order-db
  ports:
    - port: 27019
      targetPort: 27017