apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: dev
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: ataksuki/gateway:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: gateway-secret